steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west2-docker.pkg.dev/syntax-errors/dev-ai-agent-docker-images/python-hugging-face-smolagents-playground:$SHORT_SHA', '.' ]
images:
- 'europe-west2-docker.pkg.dev/syntax-errors/dev-ai-agent-docker-images/python-hugging-face-smolagents-playground:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
